name: Node.js CI/CD Pipeline

# Trigger the pipeline on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs to run in this workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (use the version that you need)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify Node.js version

      # Step 3: Install dependencies (npm install)
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (example using npm test)
      - name: Run tests
        run: npm test

      # Step 5: Deploy (this is an example, replace with your deployment process)
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Replace this with your actual deployment command, e.g., using AWS CLI or Docker
          # aws s3 cp ./build/ s3://your-bucket-name/ --recursive
